// File generated by FlutterFire CLI.
// This is a placeholder file. Run `flutterfire configure` to generate actual Firebase options.
// For now, we'll use a minimal configuration to allow the app to compile.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:placeholder:web:placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'brainland-placeholder',
    authDomain: 'brainland-placeholder.firebaseapp.com',
    storageBucket: 'brainland-placeholder.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:placeholder:android:placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'brainland-placeholder',
    storageBucket: 'brainland-placeholder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:placeholder:ios:placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'brainland-placeholder',
    storageBucket: 'brainland-placeholder.appspot.com',
    iosBundleId: 'com.mohamednagdy.brainLand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'placeholder-api-key',
    appId: '1:placeholder:macos:placeholder',
    messagingSenderId: 'placeholder',
    projectId: 'brainland-placeholder',
    storageBucket: 'brainland-placeholder.appspot.com',
    iosBundleId: 'com.mohamednagdy.brainLand',
  );
}
