// File generated by FlutterFire CLI.
// This is a placeholder file. Run `flutterfire configure` to generate actual Firebase options.
// For now, we'll use a minimal configuration to allow the app to compile.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2kplNyXOlK7xvhOREUuyTxUEW8rJbJMY',
    appId: '1:31249678994:web:69c930e6ff9a08e9ef9c4b',
    messagingSenderId: '31249678994',
    projectId: 'brain-land',
    authDomain: 'brain-land.firebaseapp.com',
    storageBucket: 'brain-land.firebasestorage.app',
    measurementId: 'G-VQ6NP8WJPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgz2VZQk-IO7c7Z0DR5VtUHPgWH2JDl9s',
    appId: '1:31249678994:android:2877e0210c582263ef9c4b',
    messagingSenderId: '31249678994',
    projectId: 'brain-land',
    storageBucket: 'brain-land.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJzjWiia10KvCIIqfBz2zjraiZWfIl7JI',
    appId: '1:31249678994:ios:50219bd982e4356fef9c4b',
    messagingSenderId: '31249678994',
    projectId: 'brain-land',
    storageBucket: 'brain-land.firebasestorage.app',
    iosBundleId: 'com.mohamednagdy.brainLand',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJzjWiia10KvCIIqfBz2zjraiZWfIl7JI',
    appId: '1:31249678994:ios:50219bd982e4356fef9c4b',
    messagingSenderId: '31249678994',
    projectId: 'brain-land',
    storageBucket: 'brain-land.firebasestorage.app',
    iosBundleId: 'com.mohamednagdy.brainLand',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2kplNyXOlK7xvhOREUuyTxUEW8rJbJMY',
    appId: '1:31249678994:web:87b8533480b9081fef9c4b',
    messagingSenderId: '31249678994',
    projectId: 'brain-land',
    authDomain: 'brain-land.firebaseapp.com',
    storageBucket: 'brain-land.firebasestorage.app',
    measurementId: 'G-7ZQ2CW0Q30',
  );

}