import '../l10n/app_localizations.dart';

/// Everything the mascot says. Each name is both the ARB key and the voice
/// file name (`assets/audio/voice/<lang>/<name>.m4a`).
enum Line {
  welcome,
  instrCount,
  instrMore,
  instrAdd,
  instrTakeAway,
  instrMissing,
  instrMissingNumber,
  instrSolve,
  instrPattern,
  instrPatternGap,
  instrMemory,
  instrShape,
  praise1,
  praise2,
  praise3,
  mistakeTryAgain,
  mistakeCountAgain,
  mistakeAddedInstead,
  mistakeSubtractedInstead,
  mistakeCompare,
  mistakePattern,
  mistakeMemory,
  mistakeShape,
  hintCountTogether,
  hintRemoveOne,
  hintPattern,
  hintMemory,
  hintShape,
  missionComplete,
  chapterComplete,
  breakTitle,
  breakBody;

  static const praise = [praise1, praise2, praise3];

  String text(AppLocalizations l) => switch (this) {
    welcome => l.welcome,
    instrCount => l.instrCount,
    instrMore => l.instrMore,
    instrAdd => l.instrAdd,
    instrTakeAway => l.instrTakeAway,
    instrMissing => l.instrMissing,
    instrMissingNumber => l.instrMissingNumber,
    instrSolve => l.instrSolve,
    instrPattern => l.instrPattern,
    instrPatternGap => l.instrPatternGap,
    instrMemory => l.instrMemory,
    instrShape => l.instrShape,
    praise1 => l.praise1,
    praise2 => l.praise2,
    praise3 => l.praise3,
    mistakeTryAgain => l.mistakeTryAgain,
    mistakeCountAgain => l.mistakeCountAgain,
    mistakeAddedInstead => l.mistakeAddedInstead,
    mistakeSubtractedInstead => l.mistakeSubtractedInstead,
    mistakeCompare => l.mistakeCompare,
    mistakePattern => l.mistakePattern,
    mistakeMemory => l.mistakeMemory,
    mistakeShape => l.mistakeShape,
    hintCountTogether => l.hintCountTogether,
    hintRemoveOne => l.hintRemoveOne,
    hintPattern => l.hintPattern,
    hintMemory => l.hintMemory,
    hintShape => l.hintShape,
    missionComplete => l.missionComplete,
    chapterComplete => l.chapterComplete,
    breakTitle => l.breakTitle,
    breakBody => l.breakBody,
  };
}
